import { SantiagoTlacotepecCentroRuta } from "./SantiagoTlacotepecCentro.js";
import { SanJuanTilapaTerminal } from "./SanJuanTilapaTerminal.js";
import { PilaresCentro } from "./PilaresCentro.js";
import { SantiagoChapultepec } from "./SantiagoChapultepec.js";
import { VillaFabrica } from "./VillaFabrica.js";
import { TenangoMexicaltzingo } from "./TenangoMexicaltzingo.js";
import { SanLuisCentroZinacantepec } from "./SanLuisCentroZinacantepec.js";
import { CentroSanFelipe } from "./CentroSanFelipe.js";
import { ElRefugioTerminal } from "./ElRefugioSantiagoTlacotepec.js";
import { TerminalLaJet } from "./TerminalLaJet.js";
import { CentroSanBartolo } from "./CentroSanBartolo.js";
import { Prepa1Pilares } from "./Prepa1Pilares.js";
export const Bus = {
  1: {
    key: 1,
    titulo: "Santiago Tlacotepec - Centro",
    tiempo: "2 - 5 min",
    costo: "$12",
    color: "#ff0000",
    img: require("../assets/Santiago-Tlacotepec-Centro-Capultitlan.jpg"),
    directions: "/Descriptions/SantiagoTlacotepecCentro",
    marks: SantiagoTlacotepecCentroRuta,
  },
  2: {
    key: 2,
    titulo: "San Juan Tilapa - Terminal",
    tiempo: "2 - 6 min",
    costo: "$12",
    img: require("../assets/SanJuanTilapaTerminal.jpeg"),
    color: "#008000",
    directions: "/Descriptions/SanJuanTilapaTerminal",
    marks: SanJuanTilapaTerminal,
  },
  3: {
    key: 3,
    titulo: "Pilares - Centro ",
    tiempo: "4 - 5 min",
    costo: "Distancia",
    img: require("../assets/PilaresCentro.jpg"),
    color: "#AA00FF",
    directions: "/Descriptions/PilaresCentro",
    marks: PilaresCentro,
  },
  4: {
    key: 4,
    titulo: "Santiago - Chapultepec",
    tiempo: "8 - 14 min",
    costo: "$14",
    img: require("../assets/SantiagoChapultepecBus.png"),
    color: "#00ffbf",
    directions: "/Descriptions/SantiagoChapultepec",
    marks: SantiagoChapultepec,
  },
  5: {
    key: 5,
    titulo: "Villa - Fabrica",
    tiempo: "7 - 12 min",
    costo: "Distancia",
    img: require("../assets/VillaFabricaCentralDeAbastos.png"),
    color: "#572364",
    directions: "/Descriptions/VillaFabrica",
    marks: VillaFabrica,
  },
  6: {
    key: 6,
    titulo: "Tenango - Mexicaltzingo",
    tiempo: "9 - 12 min",
    costo: "Distancia",
    img: require("../assets/TenangoDelValle.png"),
    color: "#f542b3",
    directions: "/Descriptions/TenangoMexicaltzingo",
    marks: TenangoMexicaltzingo,
  },
  7: {
    key: 7,
    titulo: "Centro - Las Torres - La Pila",
    tiempo: "5 - 7 min",
    costo: "$12",
    img: require("../assets/CentroTerminalTorresPila.jpg"),
    color: "#42ddf5",
    directions: "/Descriptions/CentroLasTorresLaPila",
    marks: [],
  },
  ValleDelNevado: {
    key: 8,
    titulo: "Valle del Nevado - Centro",
    tiempo: "25 - 30 min",
    costo: "Distancia",
    img: require("../assets/ValleDelNevado.jpeg"),
    color: "#b3f542",
    directions: "/Descriptions/ValleDelNevado",
    marks: [],
  },
  9: {
    key: 9,
    titulo: "San Felipe - Centro - La Joya",
    tiempo: "8 - 15 min",
    costo: "$12",
    img: require("../assets/CentroSanFelipe.png"),
    color: "#365915",
    directions: "/Descriptions/CentroSanFelipe",
    marks: CentroSanFelipe,
  },
  10: {
    key: 10,
    titulo: "El Refugio - Santiago Tlacotepec",
    tiempo: "6 - 9 min",
    costo: "$12",
    img: require("../assets/ElRefugioTerminal.png"),
    color: "#c9c567",
    directions: "/Descriptions/ElRefugioSantiagoTlacotepec",
    marks: ElRefugioTerminal,
  },
  11: {
    key: 11,
    titulo: "San Luis - Centro - Zinacantepec",
    tiempo: "8 - 14 min",
    costo: "Distancia",
    img: require("../assets/AutobusSanluisCentro.jpg"),
    color: "#8f8c8c",
    directions: "/Descriptions/SanLuisCentroZinacantepec",
    marks: SanLuisCentroZinacantepec,
  },
  12: {
    key: 12,
    titulo: "Terminal - Jet",
    tiempo: "4 - 8 min",
    costo: "$12",
    img: require("../assets/TerminalLaJet.png"),
    color: "#d192a7",
    directions: "/Descriptions/TerminalLaJet",
    marks: TerminalLaJet,
  },
  13: {
    key: 13,
    titulo: "Centro - San Bartolomé",
    tiempo: "8 - 14 min",
    costo: "$12",
    img: "",
    color: "#0000FF",
    directions: "/Descriptions/13",
    marks: CentroSanBartolo,
  },
  14: {
    key: 14,
    titulo: "Prepa 1 - Pilares",
    tiempo: "8 - 9 min",
    costo: "$12",
    img: require("../assets/Prepa1Pilares.png"),
    color: "#b0df56",
    directions: "/Descriptions/14",
    marks: Prepa1Pilares,
  },
};
